export const destinations = [
  {
    id: "ladakh",
    name: "Ladakh",
    state: "Ladakh",
    region: "High Altitude Expedition",
    category: "Mountain Adventure",
    terrain: "Cold Desert, Passes, Lakes",
    emoji: "🏍️",
    image: "/image/ladakh.jpg",
    x: 43,
    y: 14,
    labelX: 300,
    labelY: 60,
    route: "Manali → Ladakh",
    bestSeason: "May – September",
    difficulty: "Hard",
    duration: "6–8 Days",
    adventureIndex: 96,
    mustTry: "Bike ride to Pangong Lake",
    signatureExperience: "Crossing high-altitude Himalayan passes",
    highlights: ["Bike Tours", "Mountain Passes", "Camping", "Stargazing"],
  },

  {
    id: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    region: "Himalayan Escape",
    category: "Snow & Trek Adventure",
    terrain: "Mountains, Valleys, Snow Trails",
    emoji: "🏔️",
    image: "/image/manali.jpg",
    x: 36,
    y: 24,
    labelX: 220,
    labelY: 140,
    route: "Delhi → Manali",
    bestSeason: "October – February",
    difficulty: "Medium",
    duration: "4 Days",
    adventureIndex: 84,
    mustTry: "Solang Valley adventures",
    signatureExperience: "Snow activities with Himalayan views",
    highlights: ["Trekking", "Snow Sports", "ATV Rides", "Camping"],
  },

  {
    id: "bir",
    name: "Bir Billing",
    state: "Himachal Pradesh",
    region: "Sky Adventure Zone",
    category: "Aerial Adventure",
    terrain: "Hills, Valleys, Forest Slopes",
    emoji: "🪂",
    image: "/image/bir.jpg",
    x: 37,
    y: 26,
    labelX: 240,
    labelY: 195,
    route: "Delhi → Bir Billing",
    bestSeason: "March – June",
    difficulty: "Medium",
    duration: "2 Days",
    adventureIndex: 87,
    mustTry: "Paragliding flight",
    signatureExperience: "Flying over the Dhauladhar range",
    highlights: ["Paragliding", "Mountain Biking", "Nature Trails", "Camping"],
  },

  {
    id: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    region: "Adventure Capital",
    category: "River & Cliff Adventure",
    terrain: "River, Hills, Forest",
    emoji: "🌊",
    image: "/image/rishikesh.jpg",
    x: 42,
    y: 31,
    labelX: 320,
    labelY: 240,
    route: "Delhi → Rishikesh",
    bestSeason: "September – June",
    difficulty: "Medium",
    duration: "2–3 Days",
    adventureIndex: 88,
    mustTry: "White-water rafting on the Ganga",
    signatureExperience: "Rafting through rapids in the Himalayan foothills",
    highlights: ["River Rafting", "Bungee Jumping", "Camping", "Cliff Jumping"],
  },

  {
    id: "ranthambore",
    name: "Ranthambore",
    state: "Rajasthan",
    region: "Rajasthan Wilderness",
    category: "Wildlife Adventure",
    terrain: "Dry Forest, Lakes, Fort Ruins",
    emoji: "🐅",
    image: "/image/Ranthambore.jpg",
    x: 31,
    y: 47,
    labelX: 100,
    labelY: 330,
    route: "Delhi → Ranthambore",
    bestSeason: "October – June",
    difficulty: "Easy",
    duration: "2 Days",
    adventureIndex: 78,
    mustTry: "Sunrise canter safari",
    signatureExperience: "Tracking tigers through forest trails",
    highlights: [
      "Tiger Safari",
      "Wildlife Photography",
      "Jungle Trails",
      "Fort Views",
    ],
  },

  {
    id: "jaisalmer",
    name: "Jaisalmer",
    state: "Rajasthan",
    region: "Thar Desert Escape",
    category: "Desert Adventure",
    terrain: "Sand Dunes, Desert Camps",
    emoji: "🐪",
    image: "/image/jaisalmer.jpg",
    x: 22,
    y: 49,
    labelX: 70,
    labelY: 380,
    route: "Jaipur → Jaisalmer",
    bestSeason: "November – February",
    difficulty: "Easy",
    duration: "2–3 Days",
    adventureIndex: 74,
    mustTry: "Desert safari at Sam dunes",
    signatureExperience: "Camel safari under the desert sky",
    highlights: [
      "Camel Safari",
      "Dune Bashing",
      "Desert Camping",
      "Folk Nights",
    ],
  },

  {
    id: "goa",
    name: "Goa",
    state: "Goa",
    region: "Coastal Adventures",
    category: "Water Adventure",
    terrain: "Beaches, Cliffs, Backwaters",
    emoji: "🌊",
    image: "/image/goa.jpg",
    x: 35,
    y: 75,
    labelX: 120,
    labelY: 510,
    route: "Mumbai → Goa",
    bestSeason: "November – February",
    difficulty: "Easy",
    duration: "3 Days",
    adventureIndex: 80,
    mustTry: "Parasailing at Baga",
    signatureExperience: "Water sports along the Arabian Sea",
    highlights: ["Scuba Diving", "Jet Skiing", "Kayaking", "Parasailing"],
  },

  {
    id: "coorg",
    name: "Coorg",
    state: "Karnataka",
    region: "Western Ghats Escape",
    category: "Forest Adventure",
    terrain: "Coffee Estates, Hills, Waterfalls",
    emoji: "🌲",
    image: "/image/coorg.jpg",
    x: 40,
    y: 85,
    labelX: 170,
    labelY: 580,
    route: "Bangalore → Coorg",
    bestSeason: "October – March",
    difficulty: "Easy",
    duration: "3 Days",
    adventureIndex: 76,
    mustTry: "Coffee estate trail",
    signatureExperience: "Trekking through misty plantation trails",
    highlights: [
      "Waterfall Trek",
      "Camping",
      "River Rafting",
      "Plantation Walks",
    ],
  },

  {
    id: "hampi",
    name: "Hampi",
    state: "Karnataka",
    region: "Boulder Heritage Zone",
    category: "Rock Adventure",
    terrain: "Boulders, Ruins, Riverbanks",
    emoji: "🧗",
    image: "/image/hampi.jpg",
    x: 42,
    y: 73,
    labelX: 230,
    labelY: 480,
    route: "Bangalore → Hampi",
    bestSeason: "October – February",
    difficulty: "Medium",
    duration: "2–3 Days",
    adventureIndex: 79,
    mustTry: "Bouldering near ancient ruins",
    signatureExperience: "Climbing granite boulders in a heritage landscape",
    highlights: ["Bouldering", "Cycling", "Coracle Ride", "Sunset Hikes"],
  },

  {
    id: "meghalaya",
    name: "Meghalaya",
    state: "Meghalaya",
    region: "Living Root Trails",
    category: "Rainforest Adventure",
    terrain: "Caves, Waterfalls, Forest Trails",
    emoji: "🌿",
    image: "/image/meghalaya.jpg",
    x: 73,
    y: 43,
    labelX: 400,
    labelY: 310,
    route: "Guwahati → Meghalaya",
    bestSeason: "October – April",
    difficulty: "Medium",
    duration: "4 Days",
    adventureIndex: 82,
    mustTry: "Root bridge trek",
    signatureExperience: "Walking through rainforest trails and caves",
    highlights: [
      "Cave Exploration",
      "Waterfalls",
      "Trekking",
      "Root Bridges",
    ],
  },

  {
    id: "sikkim",
    name: "Sikkim",
    state: "Sikkim",
    region: "Eastern Himalayan Trails",
    category: "Mountain Trek Adventure",
    terrain: "Alpine Trails, Lakes, Monasteries",
    emoji: "🏞️",
    image: "/image/sikkim.jpg",
    x: 65,
    y: 33,
    labelX: 380,
    labelY: 235,
    route: "Bagdogra → Sikkim",
    bestSeason: "March – May",
    difficulty: "Medium",
    duration: "5 Days",
    adventureIndex: 85,
    mustTry: "Tsomgo Lake route",
    signatureExperience: "Exploring alpine trails with Kanchenjunga views",
    highlights: [
      "High Lakes",
      "Mountain Treks",
      "Yak Trails",
      "Valley Views",
    ],
  },

  {
    id: "andaman",
    name: "Andaman",
    state: "Andaman & Nicobar",
    region: "Island Exploration",
    category: "Ocean Adventure",
    terrain: "Islands, Coral Reefs, Beaches",
    emoji: "🤿",
    image: "/image/andaman.jpg",
    x: 82,
    y: 80,
    labelX: 420,
    labelY: 560,
    route: "Chennai → Port Blair",
    bestSeason: "October – May",
    difficulty: "Medium",
    duration: "5 Days",
    adventureIndex: 90,
    mustTry: "Scuba diving at Havelock",
    signatureExperience: "Diving through coral reefs and clear blue waters",
    highlights: [
      "Scuba Diving",
      "Snorkeling",
      "Island Hopping",
      "Sea Walking",
    ],
  },
];