export const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export const places = [
  {
    name: "Ladakh",
    icon: "🏔️",
    image: "/image/ladakh.jpg",
    months: ["May", "Jun", "Jul", "Aug", "Sep"],
    mood: "Cold Desert Adventure",
    note: "High passes, crystal lakes and raw mountain roads make this a dream expedition.",
    weather: "12°C",
    weatherMood: "Clear & Cold",
    rainfall: "10%",
    humidity: "40%",
    wind: "15 km/h",
    crowd: 45,
    budget: 65,
    risk: 35,
    activity: "Road Trip / Biking",
    bestFor: "Friends, Bikers",
    altitude: "11,500 ft",
    duration: "6-8 Days",
    pack: ["Thermal wear", "Windproof jacket", "Sunglasses", "Sunscreen", "Power bank", "Valid ID proof"],
    pin: { x: "35%", y: "22%" },
  },
  {
    name: "Sikkim",
    icon: "🏞️",
    image: "/image/sikkim.jpg",
    months: ["Mar", "Apr", "May", "Oct", "Nov", "Dec"],
    mood: "Clean Himalayan Views",
    note: "Clear skies, lakes and mountain roads make Sikkim feel cinematic.",
    weather: "11°C",
    weatherMood: "Cool & Clear",
    rainfall: "18%",
    humidity: "52%",
    wind: "10 km/h",
    crowd: 55,
    budget: 75,
    risk: 50,
    activity: "Mountain Route",
    bestFor: "Family, Couples",
    altitude: "5,400 ft",
    duration: "5 Days",
    pack: ["Jacket", "Medicines", "ID proof", "Shoes", "Camera", "Cash"],
    pin: { x: "66%", y: "35%" },
  },
  {
    name: "Rishikesh",
    icon: "🌊",
    image: "/image/rishikesh.jpg",
    months: ["Feb", "Mar", "Apr", "May", "Sep", "Oct", "Nov"],
    mood: "River Adrenaline",
    note: "Rafting, cliff jumping and riverside camps make it the easiest thrill escape.",
    weather: "24°C",
    weatherMood: "Pleasant",
    rainfall: "18%",
    humidity: "55%",
    wind: "10 km/h",
    crowd: 70,
    budget: 35,
    risk: 45,
    activity: "Rafting",
    bestFor: "Friends",
    altitude: "1,220 ft",
    duration: "2-3 Days",
    pack: ["Quick dry clothes", "Floaters", "Towel", "Waterproof pouch", "Sunscreen", "Extra pair"],
    pin: { x: "42%", y: "36%" },
  },
  {
    name: "Manali",
    icon: "❄️",
    image: "/image/manali.jpg",
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Oct", "Nov", "Dec"],
    mood: "Snow Valley Escape",
    note: "Snow, Solang Valley, cafés and mountain roads make it a classic adventure base.",
    weather: "8°C",
    weatherMood: "Snowy",
    rainfall: "15%",
    humidity: "52%",
    wind: "12 km/h",
    crowd: 80,
    budget: 55,
    risk: 40,
    activity: "Snow Sports",
    bestFor: "Friends, Couples",
    altitude: "6,730 ft",
    duration: "4 Days",
    pack: ["Jacket", "Gloves", "Boots", "Thermals", "Moisturizer", "Medicines"],
    pin: { x: "34%", y: "26%" },
  },
  {
    name: "Goa",
    icon: "🏄‍♀️",
    image: "/image/goa.jpg",
    months: ["Jan", "Feb", "Mar", "Nov", "Dec"],
    mood: "Saltwater Sunshine",
    note: "Beaches, water sports, sunsets and shacks make Goa the coastal adventure pick.",
    weather: "30°C",
    weatherMood: "Sunny Beach",
    rainfall: "12%",
    humidity: "68%",
    wind: "15 km/h",
    crowd: 90,
    budget: 75,
    risk: 25,
    activity: "Scuba / Parasailing",
    bestFor: "Friends, Couples",
    altitude: "Sea Level",
    duration: "3 Days",
    pack: ["Sunscreen", "Swimwear", "Sandals", "Sunglasses", "Light clothes", "Waterproof pouch"],
    pin: { x: "34%", y: "74%" },
  },
  {
    name: "Meghalaya",
    icon: "🌿",
    image: "/image/meghalaya.jpg",
    months,
    mood: "Cloud Forest Magic",
    note: "Waterfalls, caves, root bridges and misty roads keep Meghalaya alive all year.",
    weather: "19°C",
    weatherMood: "Cloudy",
    rainfall: "45%",
    humidity: "80%",
    wind: "7 km/h",
    crowd: 55,
    budget: 70,
    risk: 55,
    activity: "Root Bridge Trek",
    bestFor: "Explorers",
    altitude: "4,900 ft",
    duration: "4-5 Days",
    pack: ["Raincoat", "Waterproof bag", "Trekking shoes", "Extra socks", "Camera", "Light jacket"],
    pin: { x: "73%", y: "43%" },
  },
];